### ISSUE TITLE
Squash changes

### ISSUE THREAD

**Issue by uuf6429** [wcgallego/pecl-gearman#4]
Hey, I was wondering what's the difference from the original repository at [hjr3/pecl-gearman](https://github.com/hjr3/pecl-gearman) and I as far as I can [see here](https://github.com/mariano/pecl-gearman/compare/master...wcgallego:master), the main difference is mostly in php tests.
However, there's a lot of commits dealing with different parts of code that resulted in zero net effect.

My suggestion is to clean up commits (eg; squashing up the commits into one).

**Comment by wcgallego** [comment]
Hey @uuf6429, agreed. There's a lot of clean up to do.

The major difference was I was handling the porting over to PHP 7. hjr was kind enough to merge those changes back in.

Personally, I'm a fan of showing the warts. This was a learning experience for me and showing how I made bad calls and fixed them is important. We haven't cut a full tag yet, so that's how I would judge major differences, if you were looking to compare more closely PHP 5 port vs PHP 7 port.

I haven't cut said tag yet because I don't want to give anyone unfair expectations. On top of that, I want to get more tests in (it was sorely lacking!) and on top of that I want to split out php_gearman.c because it's one big file now and it makes groking some of it difficult and hard to manage.

I don't think this is an "issue" so I'm going to close this out. Thanks for the suggestions!
