### ISSUE TITLE
Backwards compatibility with PHP 5.x?

### ISSUE THREAD

**Issue by esabol** [wcgallego/pecl-gearman#50]
I'd seen some other PHP extension projects that support both PHP 5.x and 7.x, so I kind of expected that would be the case here. I was surprised when the code didn't compile using PHP 5.2.30. Unfortunately, my sys admin doesn't want to upgrade to PHP 7, so I'm stuck with the older version of the extension, I guess.

If you have no interest in supporting < 7.x, I recommend changing the description of the repo from "PHP wrapper to libgearman" to "PHP >= 7 wrapper to libgearman" (or something like that) and mentioning the PHP version requirement in the README, just to make it clear.

**Comment by vojta** [comment]
@esabol you can use PHP5 extension from available RPMs/repos. We used Remi on PHP 5.6 2 years ago.
And not upgrading to PHP7 is something I can't really understand, run away as fast as you can.

I think this issue should be closed.

**Comment by esabol** [comment]
> you can use PHP5 extension from available RPMs/repos.

I'm using an older version of the extension, obviously.

> I think this issue should be closed.

I agree it should be closed _once_ the description of the repo has been changed from "PHP wrapper to libgearman" to "PHP >= 7 wrapper to libgearman" (or something like that) and/or mentioning the PHP version requirement in the README. :p I don't think that's too much to ask. There's already a requirements section in the README, but it doesn't specify a minimum version of PHP.

**Comment by wcgallego** [comment]
hey @esabol, I made the explicit decision to branch away from PHP 5.x when porting pecl-gearman to 7.x. The code was already dangerously in need of clean up and while it is technically possible to build in both, it would've complicated things greatly. As pecl-gearman wasn't seeing major updates (it had been years since any commits) it was stable enough to not warrant. As mentioned above, using an older RPM or branch would suffice for building against PHP 5.x and should be feature complete.

I agree on the version - I don't think that's too much to ask! I'll pop it in

**Comment by wcgallego** [comment]
Ok, popped in. Thanks for the note
